# Generated by Django 4.1.2 on 2022-10-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celulares',
            name='marca_celular',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
