# Generated by Django 4.1.2 on 2022-11-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0002_celulares_marca_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celulares',
            name='marca_celular',
        ),
    ]
